version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - battleship-network

  service-discovery:
    build:
      context: ./Service-Discovery
    container_name: Service-Discovery
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - battleship-network

  api-gateway:
    build:
      context: ./API-Gateway
    container_name: API-Gateway
    ports:
      - "3000:3000"
    depends_on:
      - service-discovery
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - battleship-network

  battleship-service-1:
    build:
      context: ./Battleship-Service
    container_name: Battleship-Service-1
    ports:
      - "8081:8081"
    depends_on:
      - service-discovery
      - mongodb
    networks:
      - battleship-network
    environment:
      - SERVER_PORT=8081 
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017

  battleship-service-2:
    build:
      context: ./Battleship-Service
    container_name: Battleship-Service-2
    ports:
      - "8082:8082"
    depends_on:
      - service-discovery
      - mongodb
    networks:
      - battleship-network
    environment:
      - SERVER_PORT=8082 
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017

  battleship-service-3:
    build:
      context: ./Battleship-Service
    container_name: Battleship-Service-3
    ports:
      - "8083:8083"
    depends_on:
      - service-discovery
      - mongodb
    networks:
      - battleship-network
    environment:
      - SERVER_PORT=8083 
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017

  profile-service-1:
    build:
      context: ./Profile-Service
    container_name: Profile-Service-1
    ports:
      - "8084:8084"  
    depends_on:
      - service-discovery
      - postgres
    networks:
      - battleship-network
    environment:
      - SERVER_PORT=8084 
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=daniela

  profile-service-2:
    build:
      context: ./Profile-Service
    container_name: Profile-Service-2
    ports:
      - "8085:8085" 
    depends_on:
      - service-discovery
      - postgres
    networks:
      - battleship-network
    environment:
      - SERVER_PORT=8085 
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=daniela

  profile-service-3:
    build:
      context: ./Profile-Service
    container_name: Profile-Service-3
    ports:
      - "8086:8086" 
    depends_on:
      - service-discovery
      - postgres
    networks:
      - battleship-network
    environment:
      - SERVER_PORT=8086 
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=daniela

  mongodb:
    image: mongo:4.2
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - battleship-network

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=daniela
    networks:
      - battleship-network

networks:
  battleship-network:
    driver: bridge
