version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - battleship-network

  service-discovery:
    build:
      context: ./Service-Discovery
    container_name: Service-Discovery
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - battleship-network

  api-gateway:
    build:
      context: ./API-Gateway
    container_name: API-Gateway
    ports:
      - "3000:3000"
    depends_on:
      - service-discovery
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - battleship-network

  battleship-service:
    build:
      context: ./Battleship-Service
    container_name: Battleship-Service
    ports:
      - "8081:8081"
    depends_on:
      - service-discovery
      - mongodb
    networks:
      - battleship-network
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017

  profile-service:
    build:
      context: ./Profile-Service
    container_name: Profile-Service
    ports:
      - "8082:8082"
    depends_on:
      - service-discovery
      - postgres
    networks:
      - battleship-network

  mongodb:
    image: mongo:4.2
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - battleship-network

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=daniela
    networks:
      - battleship-network

networks:
  battleship-network:
    driver: bridge
